### ISSUE TITLE
Mention which number represents which date format

### ISSUE THREAD

**Issue by rebellixx** [synthead/timex_datalink_client#179]
in timex_datalink_protocol_3.md is not described what the int does at date_format ;-)
date_fomat: 1 is DD-MM-YY and 2 is YY-MM-DD

**Comment by rebellixx** [comment]
already mentioned in other issue!

**Comment by synthead** [comment]
Thank you for filing this issue! :heart: 

Here's the duplicate you mentioned :+1: https://github.com/synthead/timex_datalink_client/issues/45
