### ISSUE TITLE
Protocol 7 docs reference pcvocab.mdb, but there is no documentation on where to acquire this file

### ISSUE THREAD

**Issue by synthead** [synthead/timex_datalink_client#216]
The protocol 7 documentation references the `pcvocab.mdb` file in many examples, but there isn't any documentation on how to acquire this file.

Add a doc for how to acquire this file from the DSI e-BRAIN ISO, and link to it in the protocol 7 documentation.

**Comment by wjhrdy** [comment]
I made a script to get the file.

https://github.com/wjhrdy/timex-datalink-caldav/blob/main/bin/get_ebrain_db
