### ISSUE TITLE
extended to easily sync caldav events to the watch. 

### ISSUE THREAD

**Issue by wjhrdy** [synthead/timex_datalink_client#278]
Thanks for the excellent package!

I wanted an easy way to sync my watch with my online calendar so I made this package.
https://github.com/wjhrdy/timex-datalink-caldav/

It is opinionated toward prorocol1, eastern time and calendar events that have attendees.

I'd happily accept PRs for generalization.

**Comment by wjhrdy** [comment]
Made some updates. Now supports protocol 1, 3, 4, and 7(kinda) it uses your system time and it no longer limits to events with attendees.

**Comment by synthead** [comment]
Oh that is so cool!  I love this so much!  Very happy to see this library used!  You even added support for the e-BRAIN! :smile: 

https://github.com/synthead/timex_datalink_client/network/dependents

Thank you so much for sharing! :heart:
